apiVersion : skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: yeebay-dev
  artifacts:
    - image: gcr.io/yeebay-dev/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest : .