apiVersion : apps/v1
kind: Deployment
metadata: 
    name : auth-depl
  
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth

    spec : 
      containers: 
        - name: auth
          image:  yeebay/auth #gcr.io/yeebay-dev/auth
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
             memory: "128Mi"
             cpu: "500m"

---

apiVersion: v1

kind : Service

metadata:
  name: auth-srv
spec: 
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
